### ISSUE TITLE
Add Requires PHP field to readme.txt

### ISSUE THREAD

**Issue by Zodiac1978** [nocean/cf7-honeypot#11]
Checking with the https://wordpress.org/plugins/developers/readme-validator/ I get a warning to add a "Requires PHP" field.

**Comment by nocean** [comment]
Yeah, I got that too. It's optional, and a lot of plugins don't use it for the simple reason that unless you're requiring something higher than 5.6, it's unlikely to be used. I've tested the plugin on 5.6, 7.x and it works fine on all. I need to still test on php8 (but need to setup an environment for that). I'll add it in the next version just so it's complete. :)

**Comment by nocean** [comment]
FYI, just added this to the readme. Thanks for the push ;)
