### ISSUE TITLE
Adhere to WordPress coding standards

### ISSUE THREAD

**Issue by Zodiac1978** [nocean/cf7-honeypot#13]
There are some coding standards etablished to WP. I find it very useful to adhere to them in plugins too (although they are for core):
https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/

WP Tide will check for this also. And it will make the code more readable.

**Comment by nocean** [comment]
Great tips! Most of my coding style is just what's evolved naturally for me over the years, which I completely understand is a nightmare for others digging into it. I'll make an effort to use the standards.
