### ISSUE TITLE
Fix minor i18n issues

### ISSUE THREAD

**Issue by Zodiac1978** [nocean/cf7-honeypot#14]
I think I found two translation issues here
https://github.com/nocean/cf7-honeypot/blob/master/includes/admin.php#L181

`<?php esc_html_e(__('Honeypot for Contact Form 7'),'contact-form-7-honeypot'); ?>`

I think the parenthesis are wrong and esc_html_e is already a translation function, so it should be:
`<?php esc_html_e( 'Honeypot for Contact Form 7', 'contact-form-7-honeypot' ); ?>`

And this part:
`<?php esc_html_e('v'.HONEYPOT4CF7_VERSION); ?>`

leads to an undocumented "v" in the translation, which is highly confusing. Should this really be translatable?

You could document it with a translator comment, which would show up on translate.wordpress.org or you could use `echo` and `esc_html` without the translation feature.

The last one was the reason I created this issue, but now if I look at the code there are many more occurrences of double translation functions (like `esc_html_e( __( 'foo', 'bar' ) );` or `esc_html( __( 'foo', 'bar' ) );` which could be written as `esc_html__( 'foo', 'bar' );`

**Comment by nocean** [comment]
This is years of me neglecting how this was implemented + search-replacing in too slapdash a way. I've just gone through and updated this. Will be pushing with 2.0.3.

**Comment by nocean** [comment]
Just pushed out 2.0.3 with the i18n and general code standards cleanup.
