### ISSUE TITLE
Show if honeypot is used in form or not

### ISSUE THREAD

**Issue by Zodiac1978** [nocean/cf7-honeypot#15]
I tried to add a column in CF7 to show if the honeypot shortcode is used in the form or not. Unfortunately I wasn't able to find a way to add a column or another way to add this information.

It would make it much faster to check many forms if they already have a honeypot or not.

Maybe you find a way to add this information. I opened up an issue and have asked for a filter here:
https://github.com/takayukister/contact-form-7/issues/402

Otherwise you could maybe add a new submenu showing all forms and if they have a honeypot or not.

**Comment by Zodiac1978** [comment]
I don't see a way to add more checks to the configuration validator:
https://contactform7.com/configuration-validator-faq/

Which makes this the only option:
> Otherwise you could maybe add a new submenu showing all forms and if they have a honeypot or not.

**Comment by nocean** [comment]
Hey @Zodiac1978 - I've added this as a feature for the next version. Now that Honeypot has a dedicated options page, I can see it being too hard to wrap this into that page.

**Comment by syedaliObjects** [comment]
Hi @Zodiac1978,
I hope you are doing well.

We have added this feature in our new version 2.1.4
We have introduced a new data table that shows whether honey pot is used in this form.
