### ISSUE TITLE
Date in settings page is not localized

### ISSUE THREAD

**Issue by Zodiac1978** [nocean/cf7-honeypot#18]
The last section on the settings page is a box showing the sentence "Honeypot has stopped %1$s spam submissions since %2$s" and although the format is using the localized version via the WP settings, the month names are not translated.

This could be easily fixed with using `wp_date` instead of `date` (available since WP 5.3, so better adding a version check).
See: https://wordpress.org/support/article/formatting-date-and-time/#localization

Line affected: https://github.com/nocean/cf7-honeypot/blob/500629e0e67961a3a159e631825637b3921accc8/includes/admin.php#L322

I will happily provide a PR soon.

**Comment by Zodiac1978** [comment]
It is much simpler, because `date_i18n` would fix it for WP < 5.3 and is a wrapper for wp_date in WP 5.3+

**Comment by syedaliObjects** [comment]
Hi @Zodiac1978,
I hope you are doing well.

We have fixed this bug in our new version 2.1.4

https://github.com/wpexpertsio/cf7-honeypot/blob/new/HCF7-9/includes/admin.php#L361-L377
