### ISSUE TITLE
Detection Issue

### ISSUE THREAD

**Issue by Alexander-Shukaev** [nocean/cf7-honeypot#4]
https://github.com/nocean/cf7-honeypot/blob/bc2f10bbe703073ad8b7143c9cd1882b725edf7b/honeypot.php#L122

I believe, the above line allows bots to easily detect the usage of honeypot.  In particular, inline `style` with `display: none` and `visibility: hidden` (i.e. there is even no need for the bot to parse external CSS) and the fact that you add `-wrap` suffix to the original name of the field.  This needs to be fixed.

**Comment by nocean** [comment]
Thanks for your feedback.

I'm not sure I understand the problem with the "-wrap" suffix. "wpcf7-form-control-wrap" is a standard class on all wrapping spans for CF7 form elements. By default, CF7 uses the element's name as a class, whereas the Honeypot plugin adds the suffix "-wrap" to the element's name. Is there a good reason to remove the Honeypot-set wrap suffix?

As for the inline CSS -- adding an external CSS file to arbitrarily obfuscate these CSS rules seems like overkill. Any bot hunting for that CSS is surely going to find it. The specific rules used are a challenge. I agree, it's pretty easy for a bot to sniff them out, but they are the most widely supported and least likely to conflict with a user's other CSS.

All that said, this whole chunk of HTML is filtered, and so can be completely re-written by the user if desired, making it adaptable to specific circumstances.
