### ISSUE TITLE
Autocomplete wrong value

### ISSUE THREAD

**Issue by jackmorizo** [nocean/cf7-honeypot#5]
The Autocomplete-Value must not be "nope" 
See: https://www.w3schools.com/howto/howto_js_autocomplete.asp

https://github.com/nocean/cf7-honeypot/blob/6bc3686ca053c0083eabf21ae9ed757802f2defa/honeypot.php#L124

![autocomplete-issue](https://user-images.githubusercontent.com/5560083/57930583-a50d3d00-78b6-11e9-827c-afa83abde15c.png)

**Comment by nocean** [comment]
@jackmorizo please refer to [this support thread](https://wordpress.org/support/topic/w3c-validation-in-1-11-explanation-and-work-arounds/).
