### ISSUE TITLE
Plugin auto-deactivates on CF7 update

### ISSUE THREAD

**Issue by Zodiac1978** [nocean/cf7-honeypot#6]
In the last months for some times I experienced much more spam and found that the plugin was deactivated. But I do not find the reason why that happened.

Today I installed the update from CF7 to 5.4 and your Honeypot plugin was deactivated again. I think your `wpcf7_honeypot_has_parent_plugin` function gets triggered and therefore deactivates the plugin in the process of an CF7 update.

**Comment by Zodiac1978** [comment]
I can help to test why this happened and maybe we could change it a little bit more in this direction:
https://pento.net/2014/02/18/dont-let-your-plugin-be-activated-on-incompatible-sites/
(Old but should still be valid)

**Comment by nocean** [comment]
Hey @Zodiac1978 - much appreciate you bringing this to my attention. I'm in the middle of a big overhaul of the plugin, and will look at this bug.

**Comment by nocean** [comment]
Fixed in latest version. Thanks again for bringing this to my attention. I removed the disabling of Honeypot, and made the notice more robust (and dismissible).
