### ISSUE TITLE
Simplify load_text_domain call

### ISSUE THREAD

**Issue by Zodiac1978** [nocean/cf7-honeypot#7]
It is sufficient to just add the `load_plugin_textdomain` call without any more parameters to trigger the translation if you want to support WP < 4.6.
See: https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain

**Comment by nocean** [comment]
Much appreciated. For the next version, I'll be upping the required version to 5+, but I think I'll be keeping load_plugin_textdomain in, so will look closer at this.

**Comment by nocean** [comment]
Fixed (removed) in latest version.
