### ISSUE TITLE
Autocomplete attribute has new possible value

### ISSUE THREAD

**Issue by Zodiac1978** [nocean/cf7-honeypot#8]
We had the same issue in Antispam Bee with invalid HTML and wrong autocompletes. We have fixed this with the `new-password` attribute:
https://github.com/pluginkollektiv/antispam-bee/pull/294

Then you could remove the setting again and people still get valid HTML.

**Comment by Zodiac1978** [comment]
I just saw that Github is not having the latest version from WP.org.

@nocean Do you still use Github for development? Interested in PRs?

**Comment by nocean** [comment]
This is interesting. Will change it/test it in new version.

I've been poor at keeping Github updated. Will do better :) You should see the new version here when it gets released in a few days.

**Comment by nocean** [comment]
Fixed in latest version.
